config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#index"
  post 'newurl', to: 'pages#create', as: 'newurl'
  get 'link/:id', to: 'pages#show', as: 'url'
  get 'all', to: 'pages#all'
  delete 'del/:id', to: 'pages#destroy', as: 'del'
  get 'notfound', to: 'pages#notfound'

  get ':id', to: 'pages#redirect'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	  @url = Url.new
	end

	def show
		@url = Url.find(params[:id])
	end

	def create
		@url = Url.new(url_param)
		
		unless (@url.url.start_with?('http://',"https://"))
			
			@url.url = "http://" + @url.url
		end
		length = 40
		@url.long = SecureRandom.hex(length)
		if @url.save
			redirect_to @url
		else
			render 'new'
		end
	
	end

	def redirect
		@url = Url.where(long: params[:id]).first
		if (@url.nil?)
			render 'notfound'
		else
			redirect_to @url.url
		end
	end

	def all
		@url =Url.all
	end

	def destroy
		@url = Url.find(params[:id])
		@url.destroy
		redirect_to all_path
	end

	def notfound
	end

	private
		def url_param
			params.require(:url).permit(:url)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
	=link_to root_path, class: "navbar-brand"
		span LinkLengthener
	button.navbar-toggler data-toggle="collapse" data-target="#mobileNavbar"
		span.navbar-toggler-icon
	.collapse.navbar-collapse#mobileNavbar
		ul.navbar-nav.mr-auto
			li.nav-item
				=link_to "Home", root_path, class: "nav-link"
			li.nav-item
				=link_to "Admin", all_path, class: "nav-link"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LinkLengthener</title>
    <%= csrf_meta_tags %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/all.html.slim
.container
	table.table
		thead
			th URL
			th Longtehn
			th Option
		tdata
			- @url.each do |u|
				- url = "http://" + request.host + "/" + u.long
				tr
					td =u.url
					td =link_to u.long.truncate(20), url
					td =link_to "Delete", del_path(u), method: "Delete"
					

app/views/pages/index.html.slim
.container
	h1 Enter your link
	p Your link is too short? Not a problem. We make it looooooong for you

	= simple_form_for @url, url: newurl_path do |f|
		= f.input :url
		= f.button :submit, id: "submit_btn", class: "btn-primary"

app/views/pages/notfound.html.slim
.container
	h1.text-danger Oops!
	p The requested lengthened URL (#{request.original_url}) is not found
	br
	a.btn.btn-primary href="#{root_path}" Click Here to create a long url!

app/views/pages/show.html.slim
.container
	h1 Your Lengthen URL
	span Your Original #{@url.url}
	br
	span Your Lengthen URL:
	- url = "http://" + request.host + "/" + @url.long
	= link_to url, url